### PR TITLE
Added product store files for ADOC and Perry Ellis

### PR DESCRIPTION
**Pull request by sanjanashrivastava**
Added product store file for ADOC.

### CODE REVIEW

**Review by Amir-HC — APPROVED** [review]

**Comment by dt2patel** [comment]
Instead of writing this for every country, we should write all common configurations together and specifically break out the different configurations based on per country unique configs

**Comment by sanjanashrivastava** [comment]
Okay, sure. Updates accordingly, please check @dt2patel.

**Comment by dt2patel** [comment]
@sanjanashrivastava the same concept applies to Perry ellis and its brands where they all have the same configuration so keeping redundant tables is actually more confusing for the reader

**Comment by sanjanashrivastava** [comment]
> @sanjanashrivastava the same concept applies to Perry ellis and its brands where they all have the same configuration so keeping redundant tables is actually more confusing for the reader

@dt2patel sure. Made all the required changes, updates files and deleted irrelevant file. Also updated summary files. Please review.

**Pull request merged**
